# Generated by Django 4.1.1 on 2022-10-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='cat',
            new_name='Category',
        ),
    ]
